package storage

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/jasperaelvoet/vaporos/internal/config"
	"github.com/jasperaelvoet/vaporos/internal/extensions/descriptor"
	"github.com/jasperaelvoet/vaporos/internal/extensions/store"
	"github.com/jasperaelvoet/vaporos/internal/manifest"
)

// systemUnitDir is where the units of the merged /usr are; a variable so
// tests can relocate it.
var systemUnitDir = "/usr/lib/systemd/system"

// trialDropin bounds vos-health.service on a trial boot: a check that
// hangs then reboots and uses up a try instead of holding the box.
const trialDropin = `# Automatically generated by vos-generator: this boot is on trial.
[Unit]
JobTimeoutSec=10min
JobTimeoutAction=reboot-force
`

// generateExtensions follows the boot report (/run/vos/extensions.json),
// never intent: the system units of the extensions this boot mounted are
// wanted, and a trial boot gets the vos-health drop-in. A boot systemd-boot
// counts is a trial too, also when it mounted nothing (vos.ext=0 or
// skip-once report mode off) or its report cannot be read.
func generateExtensions(dir string) []error {
	var errs []error
	rep, err := store.LoadBootReport()
	if err != nil {
		errs = append(errs, fmt.Errorf("extensions: %w (no extension units wanted)", err))
	}
	_, cerr := os.Stat(config.BootCountVar)
	if counted := cerr == nil; counted || rep.IsTrial() || rep != nil && rep.Mode == store.ModeOSTrial {
		if err := writeDropin(dir, "vos-health.service", "50-vos-trial.conf", trialDropin); err != nil {
			errs = append(errs, fmt.Errorf("vos-health trial drop-in: %w", err))
		}
	}
	if rep == nil {
		return errs
	}
	seen := map[string]bool{}
	for _, m := range rep.Mounted {
		if !manifest.ValidExtensionID(m.ID) || seen[m.ID] {
			continue
		}
		seen[m.ID] = true
		d, err := descriptor.Load(filepath.Join(config.ExtDescriptorsDir, m.ID+".json"))
		if err == nil && d.ID != m.ID {
			err = fmt.Errorf("the descriptor is for %q", d.ID)
		}
		if err != nil {
			errs = append(errs, fmt.Errorf("extension %s: %w", m.ID, err))
			continue
		}
		for _, s := range d.Services {
			if s.Scope != "system" {
				continue
			}
			if err := wantExtensionUnit(dir, s.Unit); err != nil {
				errs = append(errs, fmt.Errorf("extension %s: %s: %w", m.ID, s.Unit, err))
			}
		}
	}
	return errs
}

// wantExtensionUnit adds the wants link a system unit's [Install] section
// would: services to multi-user.target, sockets, timers and paths to their
// own targets. An instance (a@b.service) links to its template's file.
func wantExtensionUnit(dir, unit string) error {
	file := unit
	if prefix, rest, ok := strings.Cut(unit, "@"); ok {
		ext := path.Ext(rest)
		if rest == ext {
			return fmt.Errorf("a template needs an instance")
		}
		file = prefix + "@" + ext
	}
	src := filepath.Join(systemUnitDir, file)
	if _, err := os.Stat(src); err != nil {
		return err
	}
	target := "multi-user.target"
	switch path.Ext(unit) {
	case ".socket":
		target = "sockets.target"
	case ".timer":
		target = "timers.target"
	case ".path":
		target = "paths.target"
	}
	return wantUnit(dir, target, unit, src)
}

// writeDropin writes <dir>/<unit>.d/<name>.
func writeDropin(dir, unit, name, body string) error {
	d := filepath.Join(dir, unit+".d")
	if err := os.MkdirAll(d, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(d, name), []byte(body), 0o644)
}
