package storage

import (
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/jasperaelvoet/vaporos/internal/config"
)

// Generator settings; variables so tests can relocate them.
var (
	generatorMntBase = "/var/mnt"
	sshdUnitPath     = "/usr/lib/systemd/system/sshd.service"
)

// deviceTimeout bounds how long boot waits for an adopted disk that is not
// plugged in. The mount is nofail, so a missing disk only costs this once.
const deviceTimeout = "10s"

// CLIGenerator is the systemd generator (argv: normal-dir [early-dir late-dir]).
//
// It runs very early in every boot and on each daemon-reload, before most
// of the system exists, so it only reads config.json and writes files: no
// network, no D-Bus, no lsblk. A generator that fails can take boot with
// it, so every problem is logged and the exit status is always 0; a broken
// library entry costs that library, never the machine.
func CLIGenerator(args []string) int {
	if len(args) < 1 || args[0] == "" {
		fmt.Fprintln(os.Stderr, "vos-generator: usage: vos-generator NORMAL-DIR [EARLY-DIR LATE-DIR]")
		return 0
	}
	for _, err := range generate(args[0]) {
		fmt.Fprintf(os.Stderr, "vos-generator: %v\n", err)
	}
	return 0
}

// generate writes every unit it can and returns the problems it met.
func generate(dir string) []error {
	cfg, err := config.Load()
	if err != nil {
		return []error{fmt.Errorf("%w (no library mounts or SSH generated)", err)}
	}
	var errs []error
	for _, lib := range cfg.Storage.Libraries {
		if err := writeLibraryUnit(dir, lib); err != nil {
			errs = append(errs, fmt.Errorf("library %s: %w", lib.UUID, err))
		}
	}
	if cfg.SSH.Enabled {
		if err := wantUnit(dir, "multi-user.target", "sshd.service", sshdUnitPath); err != nil {
			errs = append(errs, fmt.Errorf("ssh: %w", err))
		}
	}
	return errs
}

// writeLibraryUnit writes <escaped mountpoint>.mount, hooks it into
// local-fs.target and caps the wait for its device.
func writeLibraryUnit(dir string, lib config.Library) error {
	if !validUUID(lib.UUID) {
		return fmt.Errorf("invalid uuid")
	}
	where := lib.Mountpoint
	if !validMountpoint(where) {
		return fmt.Errorf("mountpoint %q is not a directory under %s", where, generatorMntBase)
	}
	fstype := mountType(lib.FSType)
	if !adoptable[fstype] {
		return fmt.Errorf("unsupported filesystem %q", lib.FSType)
	}
	unit, err := MountUnitName(where)
	if err != nil {
		return err
	}
	what := "/dev/disk/by-uuid/" + lib.UUID
	devUnit, err := DeviceUnitName(what)
	if err != nil {
		return err
	}

	opts := []string{"nofail", "noatime", "x-systemd.device-timeout=" + deviceTimeout}
	if fstype == "ntfs3" {
		// NTFS has no Unix owners; show everything as vapor's.
		uid := strconv.Itoa(config.GamerUID)
		opts = append(opts, "uid="+uid, "gid="+uid)
	}
	label := firstNonEmpty(unitText(lib.Label), lib.UUID)
	body := fmt.Sprintf(`# Automatically generated by vos-generator from %s.
# Adopt or remove game library disks in the VaporOS web UI (Storage).

[Unit]
Description=Game library %s
SourcePath=%s

[Mount]
What=%s
Where=%s
Type=%s
Options=%s
`, config.ConfigPath(), specifierEscape(label), specifierEscape(config.ConfigPath()),
		what, specifierEscape(where), fstype, strings.Join(opts, ","))
	if err := os.WriteFile(filepath.Join(dir, unit), []byte(body), 0o644); err != nil {
		return err
	}
	// nofail makes local-fs.target want the mount without waiting for it
	// (systemd drops the Before= ordering for nofail mounts by itself).
	if err := wantUnit(dir, "local-fs.target", unit, "../"+unit); err != nil {
		return err
	}
	// x-systemd.device-timeout= is an fstab option; systemd-fstab-generator
	// turns it into this drop-in for the device unit, and so must we.
	dropin := filepath.Join(dir, devUnit+".d")
	if err := os.MkdirAll(dropin, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dropin, "50-vos-device-timeout.conf"), []byte(fmt.Sprintf(
		"# Automatically generated by vos-generator.\n[Unit]\nJobTimeoutSec=%s\nJobRunningTimeoutSec=%s\n",
		deviceTimeout, deviceTimeout)), 0o644)
}

// wantUnit adds a <target>.wants/<unit> symlink pointing at target.
func wantUnit(dir, targetUnit, unit, linkTarget string) error {
	wants := filepath.Join(dir, targetUnit+".wants")
	if err := os.MkdirAll(wants, 0o755); err != nil {
		return err
	}
	link := filepath.Join(wants, unit)
	if err := os.Remove(link); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.Symlink(linkTarget, link)
}

// validMountpoint accepts a clean absolute path strictly below the library
// directory, so a hand-edited config can never mount over the system.
func validMountpoint(p string) bool {
	if p == "" || path.Clean(p) != p || !strings.HasPrefix(p, generatorMntBase+"/") {
		return false
	}
	for _, c := range p {
		if c < 0x20 || c == 0x7f {
			return false
		}
	}
	return true
}

// unitText makes s safe on a single unit file line.
func unitText(s string) string {
	return strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, strings.TrimSpace(s))
}

// specifierEscape doubles "%", which unit files otherwise expand.
func specifierEscape(s string) string { return strings.ReplaceAll(s, "%", "%%") }
