package brand

import (
	"encoding/json"
	"fmt"
	"strings"
)

// The web-icons target: the control center's app icons and manifest, and the
// logo partials of both UI sets.

func init() { iconTargets = append(iconTargets, iconTarget{"web-icons", webIcons}) }

const static = "internal/web/static/"

func webIcons(tf *tokensFile, syms map[string]*logoSym) (outs []output, gone []string, err error) {
	icon := syms["icon"].drawing()
	outs = []output{
		{"web-icons", static + "icon.svg", []byte(svgFile(syms["icon-small"]))},
		{"web-icons", static + "icon-180.png", encodePNG(RenderIcon(icon, 180, true))},
		{"web-icons", static + "icon-192.png", encodePNG(RenderIcon(icon, 192, false))},
	}
	icons := []manifestIcon{
		{"icon.svg", "any", "image/svg+xml", "any"},
		{"icon-192.png", "192x192", "image/png", "any"},
	}
	for _, o := range []struct {
		name, purpose string
		fullBleed     bool
	}{{"icon-512.png", "any", false}, {"icon-maskable-512.png", "maskable", true}} {
		body := encodePNG(RenderIcon(icon, 512, o.fullBleed))
		if len(body) > iconPNGBudget {
			gone = append(gone, static+o.name)
			continue
		}
		outs = append(outs, output{"web-icons", static + o.name, body})
		icons = append(icons, manifestIcon{o.name, "512x512", "image/png", o.purpose})
	}
	man, err := manifest(tf, icons)
	if err != nil {
		return nil, nil, err
	}
	outs = append(outs,
		output{"web-icons", static + "manifest.webmanifest", man},
		output{"web-icons", "internal/web/templates/partials/logo.html", []byte(nextLogoPartial(syms))},
		output{"web-icons", "internal/web/templates/legacy/partials/logo.html", []byte(legacyLogoPartial(syms))})
	return outs, gone, nil
}

// iconPNGBudget is the most a PNG may weigh to ship in the control center
// (U-11): the 512 and maskable icons are left out of web-icons above it.
const iconPNGBudget = 12_000

// ---- SVG markup

// svgPaths writes a drawing's paths for an <svg> that already sets
// fill="none" and round caps and joins.
func svgPaths(s *logoSym) string {
	var b strings.Builder
	for _, p := range s.Paths {
		b.WriteString(`<path d="` + p.D + `"`)
		if p.Fill != "none" {
			b.WriteString(` fill="` + p.Fill + `"`)
		}
		if p.Stroke != "" && p.Stroke != "none" {
			b.WriteString(` stroke="` + p.Stroke + `" stroke-width="` + p.Width + `"`)
		}
		b.WriteString("/>")
	}
	return b.String()
}

func vbAttr(s *logoSym) string {
	return goF32(s.ViewBox[0]) + " " + goF32(s.ViewBox[1]) + " " + goF32(s.ViewBox[2]) + " " + goF32(s.ViewBox[3])
}

const svgPaint = `fill="none" stroke-linecap="round" stroke-linejoin="round"`

// svgFile is a standalone SVG of one drawing: no ids, no style.
func svgFile(s *logoSym) string {
	return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="` + vbAttr(s) + `" ` + svgPaint + `>` + svgPaths(s) + "</svg>\n"
}

// inlineSVG is a drawing for a page: decorative (the link or heading next to
// it carries the name), sized by CSS through class, with width and height as
// the fallback.
func inlineSVG(s *logoSym, class string, w, h int) string {
	return fmt.Sprintf(`<svg class="%s" viewBox="%s" width="%d" height="%d" %s aria-hidden="true" focusable="false">%s</svg>`,
		class, vbAttr(s), w, h, svgPaint, svgPaths(s))
}

const partialHeader = `{{- /* Code generated by go test ./internal/brand -run TestGenerateDesign (VOS_GEN_DESIGN=1) from design/logo.svg. DO NOT EDIT.
`

func nextLogoPartial(syms map[string]*logoSym) string {
	word := syms["wordmark"]
	ww := int(float32(20)*word.ViewBox[2]/word.ViewBox[3] + 0.5)
	return partialHeader + `  The mark for the new UI: "logo" is the compact mark (the white-hot core in one
  amber band), "logo-mono" the one-colour core V in currentColor, "wordmark" Vapor in
  currentColor and OS in smoke. No ids and no gradients, so a page may show each any
  number of times; CSS sizes them through .logo and .wordmark and may recolour paths. */ -}}
{{define "logo"}}` + inlineSVG(syms["mark"], "logo", 24, 24) + `{{end}}
{{define "logo-mono"}}` + inlineSVG(syms["mono"], "logo", 24, 24) + `{{end}}
{{define "wordmark"}}` + inlineSVG(word, "wordmark", ww, 20) + `{{end}}
`
}

func legacyLogoPartial(syms map[string]*logoSym) string {
	return partialHeader + `  The legacy UI's logo: the small app icon (the tile, two isotherms and the compact
  mark), sized and rounded by the legacy stylesheet's .logo rules. No ids. */ -}}
{{define "logo"}}` + inlineSVG(syms["icon-small"], "logo", 32, 32) + `{{end}}
`
}

// ---- manifest

type manifestIcon struct {
	Src     string `json:"src"`
	Sizes   string `json:"sizes"`
	Type    string `json:"type"`
	Purpose string `json:"purpose"`
}

func manifest(tf *tokensFile, icons []manifestIcon) ([]byte, error) {
	canvas, err := tf.roleHex("canvas", "dark")
	if err != nil {
		return nil, err
	}
	m := struct {
		ID              string         `json:"id"`
		Name            string         `json:"name"`
		ShortName       string         `json:"short_name"`
		Description     string         `json:"description"`
		StartURL        string         `json:"start_url"`
		Scope           string         `json:"scope"`
		Display         string         `json:"display"`
		BackgroundColor string         `json:"background_color"`
		ThemeColor      string         `json:"theme_color"`
		Icons           []manifestIcon `json:"icons"`
	}{"/", tf.App.Name, tf.App.ShortName, tf.App.Description, "/", "/", "standalone", canvas, canvas, icons}
	b, err := json.MarshalIndent(m, "", "  ")
	return append(b, '\n'), err
}
