package brand

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
)

// The UI icon set: design/icons/<name>.svg, one drawing each, becomes the
// control center's sprite (internal/web/icons_gen.go, web-icons) and the
// website's copy for pictures of the control center (icons.gen.ts, site-icons).

func init() {
	iconTargets = append(iconTargets,
		iconTarget{"web-icons", func(*tokensFile, map[string]*logoSym) ([]output, []string, error) {
			src, _, err := uiIcons()
			return []output{{"web-icons", "internal/web/icons_gen.go", src}}, nil, err
		}},
		iconTarget{"site-icons", func(*tokensFile, map[string]*logoSym) ([]output, []string, error) {
			_, ts, err := uiIcons()
			return []output{{"site-icons", "website/src/lib/icons.gen.ts", ts}}, nil, err
		}})
}

// ---- design/icons

const iconsDir = "design/icons"

var iconElems = []string{"path", "circle", "ellipse", "rect", "line", "polyline", "polygon"}
var iconAttrs = []string{"d", "cx", "cy", "r", "rx", "ry", "x", "y", "width", "height", "x1", "y1", "x2", "y2", "points"}

// readUIIcons returns every design/icons/<name>.svg's inner markup, by name.
// The markup is taken verbatim, so the sprite carries exactly the drawing.
func readUIIcons() (map[string]string, error) {
	files, err := filepath.Glob(filepath.Join(repoRoot, iconsDir, "*"))
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, f := range files {
		name, ok := strings.CutSuffix(filepath.Base(f), ".svg")
		if !ok || !kebabRe.MatchString(name) {
			return nil, fmt.Errorf("%s/%s: icons are <kebab-case name>.svg", iconsDir, filepath.Base(f))
		}
		b, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		inner, err := iconInner(b)
		if err != nil {
			return nil, fmt.Errorf("%s/%s: %w", iconsDir, filepath.Base(f), err)
		}
		out[name] = inner
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s holds no icons", iconsDir)
	}
	return out, nil
}

func iconInner(b []byte) (string, error) {
	dec := xml.NewDecoder(bytes.NewReader(b))
	depth, start := 0, int64(-1)
	for {
		tok, err := dec.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", err
		}
		switch tok := tok.(type) {
		case xml.StartElement:
			if depth == 0 {
				if tok.Name.Local != "svg" {
					return "", fmt.Errorf("the root must be <svg>")
				}
				vb := ""
				for _, a := range tok.Attr {
					if a.Name.Local == "viewBox" {
						vb = a.Value
					}
				}
				if vb != "0 0 24 24" {
					return "", fmt.Errorf(`the root needs viewBox="0 0 24 24"`)
				}
				start = dec.InputOffset()
			} else {
				if depth > 1 || !slices.Contains(iconElems, tok.Name.Local) {
					return "", fmt.Errorf("<%s>: an icon holds only %s, not nested", tok.Name.Local, strings.Join(iconElems, ", "))
				}
				for _, a := range tok.Attr {
					if a.Name.Space != "" || !slices.Contains(iconAttrs, a.Name.Local) {
						return "", fmt.Errorf("<%s %s>: shapes carry geometry only; the .icon class strokes them", tok.Name.Local, a.Name.Local)
					}
				}
			}
			depth++
		case xml.EndElement:
			depth--
		case xml.CharData:
			if depth > 0 && len(bytes.TrimSpace(tok)) > 0 {
				return "", fmt.Errorf("text is not allowed in an icon")
			}
		}
	}
	end := bytes.LastIndex(b, []byte("</svg>"))
	if start < 0 || end < int(start) {
		return "", fmt.Errorf("not an <svg>…</svg> document")
	}
	inner := string(b[start:end])
	if strings.ContainsAny(inner, "`\n") || strings.TrimSpace(inner) == "" {
		return "", fmt.Errorf("the drawing must be one line of shapes without backquotes")
	}
	return inner, nil
}

// uiIcons renders internal/web/icons_gen.go and website/src/lib/icons.gen.ts.
func uiIcons() (goSrc, ts []byte, err error) {
	icons, err := readUIIcons()
	if err != nil {
		return nil, nil, err
	}
	names := make([]string, 0, len(icons))
	for n := range icons {
		names = append(names, n)
	}
	sort.Strings(names)
	var g strings.Builder
	g.WriteString("// Code generated by go test ./internal/brand -run TestGenerateDesign (VOS_GEN_DESIGN=1) from design/icons/*.svg. DO NOT EDIT.\n\n")
	g.WriteString(`package web

// iconPaths is the UI's icon set: 24×24 outline drawings, stroked with
// currentColor by the .icon CSS class. Each page inlines them once as an SVG
// sprite of <symbol>s, and markup (server or JS) references them with
// <use href="#i-name">, so an icon costs a few bytes wherever it is used and
// needs no extra request. The code that does that is in icons.go. Both UI
// sets use these names, so while both exist names are only ever added: add
// design/icons/<name>.svg and regenerate.
var iconPaths = map[string]string{
`)
	for _, n := range names {
		fmt.Fprintf(&g, "\t%q: `%s`,\n", n, icons[n])
	}
	g.WriteString("}\n")
	goSrc, err = format.Source([]byte(g.String()))
	if err != nil {
		return nil, nil, err
	}
	var t strings.Builder
	t.WriteString("// Code generated from design/icons/*.svg by go test ./internal/brand (VOS_GEN_DESIGN=1). DO NOT EDIT.\n")
	t.WriteString("// The control center's icon set: 24×24 shapes to stroke with currentColor at width 2 with round\n")
	t.WriteString("// caps and joins, for pictures of the control center on the site.\n\n")
	t.WriteString("export const ccIconPaths = {\n")
	for _, n := range names {
		fmt.Fprintf(&t, "  %s: %s,\n", tsKey(n), tsString(icons[n]))
	}
	t.WriteString("} as const;\n\nexport type CCIconName = keyof typeof ccIconPaths;\n")
	return goSrc, []byte(t.String()), nil
}
