#!/usr/bin/env node
// Parity: every behaviour of today's control center has a flow ID, and every
// ID needs a passing flow before the switch (GATE-2b).
//
//   node tools/web/e2e/parity.mjs --generate [--plan=DIR]
//       rewrite e2e/parity.json from the plan: the parity table in
//       spec-cc-screens.md §20 and MASTER-PLAN.md §6.7's additions
//       (default DIR ~/.claude/plans/vaporos-redesign)
//   node tools/web/e2e/parity.mjs [--report=report.json] [--strict]
//       list the IDs without a spec flow (and, with a run's report, those
//       whose flow did not pass). --strict or VOS_WEB_STRICT=1 exits 1 on any.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { parseArgs } from './lib/run-helpers.mjs';

const here = dirname(fileURLToPath(import.meta.url));
export const PARITY_FILE = join(here, 'parity.json');

// The prefix of a flow ID names the agent that owns its spec (SCN §20).
export const OWNERS = { 'HOME-': 'C1', 'DEV-': 'C2', 'SCR-': 'C3', 'SYS-': 'C4', 'ENTRY-': 'C5', 'SHELL-': 'C0b' };
export const ID_RE = /^(HOME|DEV|SCR|SYS|ENTRY|SHELL)-[a-z0-9]+(?:-[a-z0-9]+)*$/;

// BEYOND_PARITY: flows of what the eight-page UI never had (System ›
// Extensions) have no parity row: GATE-2b is about the switch.
export const BEYOND_PARITY = /^SYS-ext-[a-z0-9]+(?:-[a-z0-9]+)*$/;

export function owner(id) {
  const p = Object.keys(OWNERS).find((k) => id.startsWith(k));
  return p ? OWNERS[p] : '';
}

const cell = (s) => s.trim().replace(/\\\|/g, '|');

// parseScreens reads SCN §20's rows: | n | today | new home | `ID` |
export function parseScreens(md) {
  const start = md.indexOf('## 20. Parity table');
  if (start < 0) throw new Error('spec-cc-screens.md has no "## 20. Parity table"');
  const rows = [];
  let group = '';
  for (const line of md.slice(start).split('\n').slice(1)) {
    if (/^## /.test(line)) break;
    const g = line.match(/^\| \*\*(.+?)\*\*/);
    if (g) {
      group = g[1].replace(/\s*\(.*\)$/, '');
      continue;
    }
    const m = line.match(/^\|\s*(\d+)\s*\|(.*)\|(.*)\|\s*`([A-Z]+-[a-z0-9-]+)`\s*\|\s*$/);
    if (m) rows.push({ id: m[4], row: Number(m[1]), group, today: cell(m[2]), home: cell(m[3]) });
  }
  return rows;
}

// parseAdditions reads MASTER-PLAN §6.7's list of extra flow IDs.
export function parseAdditions(md) {
  const start = md.indexOf('### 6.7 ');
  if (start < 0) throw new Error('MASTER-PLAN.md has no "### 6.7" section');
  const text = md.slice(start).split('\n').slice(1).join('\n').split(/\n#{2,3} /)[0];
  const out = [];
  for (const m of text.matchAll(/`([A-Z]+-[a-z0-9-]+)`(\s*\(only if [^)]*\))?/g)) {
    out.push({ id: m[1], conditional: m[2] ? m[2].trim().replace(/^\(|\)$/g, '') : undefined });
  }
  return out;
}

export function build(screensMd, planMd) {
  const flows = [];
  for (const r of parseScreens(screensMd)) flows.push({ ...r, owner: owner(r.id), source: 'SCN §20' });
  for (const a of parseAdditions(planMd)) {
    if (flows.some((f) => f.id === a.id)) continue;
    flows.push({ id: a.id, owner: owner(a.id), source: 'MASTER-PLAN §6.7', ...(a.conditional ? { conditional: a.conditional } : {}) });
  }
  return {
    about: 'Every flow ID GATE-2b needs a passing flow for. Generated by node tools/web/e2e/parity.mjs --generate from spec-cc-screens.md §20 and MASTER-PLAN.md §6.7; do not edit by hand.',
    owners: OWNERS,
    flows,
  };
}

// passing is the set of flow IDs that ran and passed in every run: a flow
// that passes at 1440 but fails at 390 is not passing.
export function passing(runs) {
  const failed = new Set(runs.filter((f) => !f.ok).map((f) => f.id));
  return new Set(runs.filter((f) => f.ok && !failed.has(f.id)).map((f) => f.id));
}

// specFlowIDs lists the flow IDs the spec files define, by spec.
export async function specFlowIDs(dir = join(here, 'specs')) {
  const out = new Map();
  let files = [];
  try {
    files = readdirSync(dir).filter((f) => f.endsWith('.spec.mjs'));
  } catch {
    return out;
  }
  for (const f of files.sort()) {
    const mod = await import(pathToFileURL(join(dir, f)).href);
    for (const flow of mod.default ?? []) out.set(flow.id, f);
  }
  return out;
}

async function main() {
  const args = parseArgs(process.argv.slice(2), { generate: false, plan: join(homedir(), '.claude', 'plans', 'vaporos-redesign'), report: '', strict: false });
  if (args.generate) {
    const data = build(readFileSync(join(args.plan, 'spec-cc-screens.md'), 'utf8'), readFileSync(join(args.plan, 'MASTER-PLAN.md'), 'utf8'));
    writeFileSync(PARITY_FILE, JSON.stringify(data, null, 2) + '\n');
    console.log(`parity: wrote ${data.flows.length} flow IDs to ${PARITY_FILE}`);
    return 0;
  }
  const { flows } = JSON.parse(readFileSync(PARITY_FILE, 'utf8'));
  const specs = await specFlowIDs();
  const missing = flows.filter((f) => !specs.has(f.id) && !f.conditional);
  let notPassing = [];
  if (args.report) {
    notPassing = flows.filter((f) => specs.has(f.id) && !passing(JSON.parse(readFileSync(args.report, 'utf8')).flows).has(f.id));
  }
  const byOwner = {};
  for (const f of missing) (byOwner[f.owner] ??= []).push(f.id);
  const conditional = flows.filter((f) => f.conditional && !specs.has(f.id));
  console.log(
    `parity: ${flows.length} IDs, ${flows.filter((f) => specs.has(f.id)).length} with a spec flow, ${missing.length} without` +
      (conditional.length ? `, ${conditional.length} conditional (${conditional.map((f) => `${f.id}: ${f.conditional}`).join('; ')})` : ''),
  );
  for (const [o, ids] of Object.entries(byOwner)) console.log(`  ${o}: ${ids.join(' ')}`);
  for (const f of notPassing) console.log(`  not passing in ${args.report}: ${f.id}`);
  const strict = args.strict || process.env.VOS_WEB_STRICT === '1';
  return strict && (missing.length || notPassing.length) ? 1 : 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) process.exit(await main());
